### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by bettercallazamat** [flpfar/smashing-magazine-heatmap#1]
Good start, suggestions to think about in progress:

1. Use 2 spaces indentation and alphabetic order in CSS properties
2. Check grid related section with stickler
3. Try to use fallback font families
4. Try use padding and positioning of text in divs correctly
5. Use RGB or HEX colors instead of named colors

Keep good work.

**Comment by flpfar** [comment]
Everything solved, guys. Thanks for reviewing!
